export const packingTodos = [
    // ex. packing for a weekend trip
    "Passport/Visa",
    "Driver's License/ID",
    "Travel insurance information",
    "Health insurance card",
    "Emergency contacts and addresses",
    "Printed reservation confirmations (accommodation, car rental, activities)",
    "Maps and directions (if not using a smartphone)",
    "Credit cards (Visa as you mentioned)",
    "Small amount of local currency (pesos) for emergencies or small vendors",
    "Wallet",
    "Underwear",
    "Socks",
    "Sleepwear",
    "T-shirts",
    "Casual shirts/blouses",
    "Dress shirts/blouses for fancy dinners",
    "Pants/jeans",
    "Shorts",
    "Dresses/skirts",
    "Sweaters/jackets for cooler evenings",
    "Swimwear (if applicable)",
    "Comfortable walking shoes",
    "Dress shoes",
    "Sandals/flip-flops",
    "Hats/caps",
    "Sunglasses",
    "Belts",
    "Toothbrush, toothpaste, floss",
    "Deodorant",
    "Shampoo and conditioner",
    "Soap/body wash",
    "Skincare products (moisturizer, face wash)",
    "Hairbrush/comb",
    "Hair styling products",
    "Shaving supplies",
    "Feminine hygiene products",
    "Makeup and makeup remover",
    "Sunscreen",
    "Insect repellent",
    "Personal hygiene items",
    "Hand sanitizer",
    "Prescription medications with original bottles/labels",
    "Pain relievers (like ibuprofen or acetaminophen)",
    "Allergy medications",
    "Motion sickness pills if needed",
    "First aid kit (band-aids, antiseptic wipes, etc.)",
    "Vitamins",
    "Smartphone and charger",
    "Headphones/earbuds",
    "Portable power bank",
    "Camera and charger",
    "Memory cards",
    "Travel adapters and converters",
    "Daypack/backpack",
    "Books/e-books",
    "Travel pillow",
    "Travel blanket",
    "Eye mask and earplugs",
    "Water bottle",
    "Snacks",
    "Pens and a notebook",
    "Laundry bag",
    "Quick-dry towel",
    "Beach towel (if applicable)",
    "Umbrella and/or raincoat",
    "Spanish audio lessons",
    "Playlist or music app for entertainment",
    "Car charger for devices",
    "GPS device or smartphone with GPS capabilities",
    "Snacks and beverages",
    "Small trash bags",
];

export const morningTodos = [
    "Make bed",
    "Drink a glass of water",
    "Brush teeth",
    "Get dressed",
    "Go to the gym",
    "Eat breakfast",
    "Shower",
    "Plan work day tasks",
];

const all = {
    packingTodos,
    morningTodos,
};

export default all;
